# Generated by Django 4.1 on 2022-08-27 16:58

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_video_text_image_file_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["order"],
                "verbose_name": "Content",
                "verbose_name_plural": "Contents",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=courses.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=courses.fields.OrderField(blank=True, null=True),
        ),
    ]
