# Generated by Django 4.1 on 2022-08-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="students",
        ),
    ]
