# Generated by Django 4.1 on 2022-08-31 04:43

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_course_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="order",
            field=courses.fields.OrderField(blank=True, db_index=True, null=True),
        ),
    ]
